// This file is auto-generated by Convex
import {
  QueryCtx as GenericQueryCtx,
  MutationCtx as GenericMutationCtx,
} from "convex/server";
import { DataModel } from "./dataModel";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;

export { query, mutation, internalQuery, internalMutation } from "convex/server";
