// This file is auto-generated by Convex
import {
  queryGeneric,
  mutationGeneric,
  internalQueryGeneric,
  internalMutationGeneric,
} from "convex/server";

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const internalQuery = internalQueryGeneric;
export const internalMutation = internalMutationGeneric;
